### ISSUE TITLE
Attempting to scroll upwards on  list view invokes pull to refresh 

### ISSUE THREAD

**Issue by dev01prishusoft** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#23]
Attempting to scroll upwards on  list view invokes pull to refresh. Due to that i am not able to scroll up smoothly 

is there any solution for that ?

My xaml structure as below

`<controls:PullToRefreshLayout>
<scrollview>
<stacklayout>
<listview></listview>
</stacklayout>
</scrollview>
</controls:PullToRefreshLayout>`

**Comment by rudyspano** [comment]
Hello, you should not use the controls:PullToRefreshLayout with a listview inside (This is why you have this problem). 
Instead, you should use XF Listview PullToRefresh feature https://developer.xamarin.com/guides/xamarin-forms/user-interface/listview/interactivity/#Pull_to_Refresh . Moreover, it's often a bad practice to have a listview inside a ScrollView: Listview has it's own ScrollView embedded.

**Comment by guiu23** [comment]
Hi all, I have the same problem with this code:

```
    <ContentPage.Content>
        <controls:PullToRefreshLayout>
            <Grid>
                <Grid>
                    <StackLayout>...</StackLayout>
                </Grid>
                <ScrollView> ... </ScrollView>
            </Grid>
        </controls:PullToRefreshLayout>
    </ContentPage.Content>
```

The case is that I can't insert the refresh option in ScrollView, because I also want to refresh from the previous StackLayout if the user scroll upwards from there. The problem to fix should be only let refresh if scroll view is at maximum top. Do you know if it's possible to do it?
